name: cla
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cla-acknowledgement:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          persist-credentials: false
      - run: rustup toolchain install 1.85.0 --profile minimal
      - run: rustup default 1.85.0
      - env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: cargo run --locked --offline -p xtask -- cla-ack
